spring:
  application:
    name: vkr

  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:36091/railway
    username: postgres
    password: slWiwEQgIIxwZsEQOjOmklLdRfBNygWc
    driver: class-name=org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show:
      sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true