version: "3.9"
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "vkr"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - vkr-pgdata-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  vkr-pgdata-volume:
    name: docker_vkr-pgdata